language: go
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - master
os:
  - linux
matrix:
 fast_finish: true
 allow_failures:
   - go: master

sudo: false

notifications:
  email:
    on_success: always
    on_failure: always

